import { defineCollection } from 'astro:content';
import { docsLoader } from '@astrojs/starlight/loaders';
import { docsSchema } from '@astrojs/starlight/schema';

// docs/references (the docs/references/errors/ error catalog), docs/adr/,
// docs/DEPLOYMENT.md, docs/runbooks/, and docs/security/ are sourced via
// src/content/docs symlinks. Starlight's docsLoader() (rather than a raw
// glob with a custom base) is required for the autogenerated sidebar/route
// tree to populate correctly from the symlinked paths.
export const collections = {
  docs: defineCollection({ loader: docsLoader(), schema: docsSchema() }),
};
