import { defineCollection } from 'astro:content';
import { docsLoader } from '@astrojs/starlight/loaders';
import { docsSchema } from '@astrojs/starlight/schema';

// docs/references (the docs/references/errors/ error catalog) is sourced via
// the src/content/docs/references symlink. Starlight's docsLoader() (rather
// than a raw glob with a custom base) is required for the autogenerated
// sidebar/route tree to populate correctly from the symlinked path.
export const collections = {
  docs: defineCollection({ loader: docsLoader(), schema: docsSchema() }),
};
