---
name: Spell Check

"on":
  pull_request:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  typos:
    name: Check Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        # v7.0.0
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Check spelling with typos
        # master (latest)
        uses: crate-ci/typos@8a48f81b6c64dcfea44b3633223084c4be58ac5f
        continue-on-error: true
        with:
          files: .
          config: .typos.toml
