---
name: Spell Check

"on":
  pull_request:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  typos:
    name: Check Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        # v7.0.0
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Check spelling with typos
        # master (latest)
        uses: crate-ci/typos@d43b6c087ac471e2ea7b8af622ff15f05c0c365b
        continue-on-error: true
        with:
          files: .
          config: .typos.toml
